Unsapa\IPWBundle\Entity\Exam:
    properties:
        title:
            - NotNull: ~
            - MinLength:
                limit: 3
                message: 3 caractères minimums.
        state:
            - NotNull: ~
        promo:
            - NotNull: ~
        resp:
            - NotNull: ~
        coef:
            - NotNull: ~
            - Type: 
                type: float
                message: Le coefficient doit être un nombre.

Unsapa\IPWBundle\Entity\Record:
    properties:
        student:
            - NotNull: ~
        mark:
            - Type:
                type: float
                message: La note doit être un nombre.
        exam: 
            - NotNull: ~
        document:
            - NotNull: ~
            - File:
                maxSize: 10M
                mimeTypes: [application/pdf, application/x-pdf]
                mimeTypesMessage: Types de fichier valide : PDF
